// <auto-generated />
using System;
using ClothingStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingStore.Data.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260614154550_UniqueEmailConstraint")]
    partial class UniqueEmailConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingStore.Models.Entities.Account", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ACCOUNTS", t =>
                        {
                            t.HasTrigger("TR_Accounts_UpdatedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.AccountRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ACCOUNTROLES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("SessionKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CartID");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_Cart_Active")
                        .HasFilter("[CustomerId] IS NOT NULL AND [Status] = 'Active'");

                    b.HasIndex("SessionKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Carts_SessionKey")
                        .HasFilter("[SessionKey] IS NOT NULL");

                    b.ToTable("CARTS", t =>
                        {
                            t.HasTrigger("TR_Carts_UpdatedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"));

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("VariantID")
                        .HasColumnType("int");

                    b.HasKey("CartItemID");

                    b.HasIndex("VariantID");

                    b.HasIndex("CartID", "VariantID")
                        .IsUnique()
                        .HasDatabaseName("UQ_CartVariant");

                    b.ToTable("CARTITEMS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .HasDatabaseName("IX_Categories_CategoryName");

                    b.HasIndex("ParentCategoryID")
                        .HasDatabaseName("IX_Categories_ParentCategoryId");

                    b.ToTable("CATEGORIES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ChatMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFromUser")
                        .HasColumnType("bit");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("SessionID");

                    b.ToTable("CHATMESSAGES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ChatSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.HasIndex("UserId");

                    b.ToTable("CHATSESSIONS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Color", b =>
                {
                    b.Property<int>("ColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorID"));

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ColorID");

                    b.ToTable("COLORS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Coupon", b =>
                {
                    b.Property<int>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponID"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinOrderValue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("CouponID");

                    b.ToTable("COUPONS", t =>
                        {
                            t.HasTrigger("TR_Coupons_UpdatedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.CouponUsage", b =>
                {
                    b.Property<int>("UsageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsageID"));

                    b.Property<int>("CouponID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UsageID");

                    b.HasIndex("CouponID")
                        .HasDatabaseName("IX_CouponUsages_CouponId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderID");

                    b.HasIndex("CouponID", "OrderID")
                        .IsUnique()
                        .HasDatabaseName("UQ_Coupon_Order");

                    b.ToTable("COUPONUSAGES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MembershipID")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("MembershipID");

                    b.ToTable("CUSTOMERS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.DiscountProgram", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProgramID");

                    b.ToTable("DISCOUNTPROGRAMS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.GoodsIssue", b =>
                {
                    b.Property<int>("IssueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueID"));

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("IssueID");

                    b.HasIndex("OrderID");

                    b.ToTable("GOODSISSUES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.GoodsIssueDetail", b =>
                {
                    b.Property<int>("IssueDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueDetailID"));

                    b.Property<int>("IssueID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VariantID")
                        .HasColumnType("int");

                    b.HasKey("IssueDetailID");

                    b.HasIndex("VariantID");

                    b.HasIndex("IssueID", "VariantID")
                        .IsUnique()
                        .HasDatabaseName("UQ_IssueVariant");

                    b.ToTable("GOODSISSUEDETAILS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.GoodsReceipt", b =>
                {
                    b.Property<int>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptID"));

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ReceiptID");

                    b.HasIndex("SupplierID");

                    b.ToTable("GOODSRECEIPTS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.GoodsReceiptDetail", b =>
                {
                    b.Property<int>("ReceiptDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptDetailID"));

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptID")
                        .HasColumnType("int");

                    b.Property<int>("VariantID")
                        .HasColumnType("int");

                    b.HasKey("ReceiptDetailID");

                    b.HasIndex("VariantID");

                    b.HasIndex("ReceiptID", "VariantID")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReceiptVariant");

                    b.ToTable("GOODSRECEIPTDETAILS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.InventoryTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockAfterTransaction")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VariantID")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("VariantID", "TransactionType")
                        .HasDatabaseName("IX_InventoryTx_VariantId");

                    b.ToTable("INVENTORYTRANSACTIONS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Membership", b =>
                {
                    b.Property<int>("MembershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipID"));

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("MaxPoint")
                        .HasColumnType("int");

                    b.Property<string>("MembershipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinPoint")
                        .HasColumnType("int");

                    b.HasKey("MembershipID");

                    b.ToTable("MEMBERSHIPS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedShipperId")
                        .HasColumnType("int");

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryFailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryFailureReasonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingRecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShippingStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingWard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("AssignedShipperId");

                    b.HasIndex("CartID")
                        .IsUnique()
                        .HasDatabaseName("UX_Order_Cart");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("CustomerId", "OrderDate")
                        .HasDatabaseName("IX_Orders_CustomerId");

                    b.HasIndex("OrderStatus", "OrderDate")
                        .HasDatabaseName("IX_Orders_OrderStatus");

                    b.ToTable("ORDERS", t =>
                        {
                            t.HasTrigger("TR_Orders_UpdatedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                    b.Property<string>("ColorNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SKUSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeCodeSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VariantID")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("VariantID")
                        .HasDatabaseName("IX_OrderDetails_VariantId");

                    b.HasIndex("OrderID", "VariantID")
                        .IsUnique()
                        .HasDatabaseName("UQ_OrderVariant");

                    b.ToTable("ORDERDETAILS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.OrderStatusHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("HistoryID");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("OrderID");

                    b.ToTable("ORDERSTATUSHISTORY");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ExternalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionID");

                    b.HasIndex("ExternalID")
                        .IsUnique();

                    b.HasIndex("OrderID")
                        .IsUnique()
                        .HasDatabaseName("UX_One_Success_Transaction_Per_Order")
                        .HasFilter("[Status] = 'Success'");

                    b.ToTable("TRANSACTIONS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("CareInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgramID")
                        .HasColumnType("int");

                    b.Property<string>("SearchNormalizedName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID")
                        .HasDatabaseName("IX_Products_CategoryId");

                    b.HasIndex("ProgramID");

                    b.HasIndex("SearchNormalizedName")
                        .HasDatabaseName("IX_Products_SearchNormalizedName");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("PRODUCTS", t =>
                        {
                            t.HasTrigger("TR_Products_UpdatedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ProductImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("VariantID")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("VariantID", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductImage_Order");

                    b.ToTable("PRODUCTIMAGES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ProductRelationship", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("LinkedProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "LinkedProductID");

                    b.HasIndex("LinkedProductID");

                    b.ToTable("PRODUCTRELATIONSHIPS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ProductVariant", b =>
                {
                    b.Property<int>("VariantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantID"));

                    b.Property<int>("ColorID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SizeID")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VariantID");

                    b.HasIndex("ColorID")
                        .HasDatabaseName("IX_ProductVariants_ColorId");

                    b.HasIndex("ProductID")
                        .HasDatabaseName("IX_ProductVariants_ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("SizeID")
                        .HasDatabaseName("IX_ProductVariants_SizeId");

                    b.HasIndex("ProductID", "SizeID", "ColorID")
                        .IsUnique()
                        .HasDatabaseName("UQ_ProductVariant");

                    b.ToTable("PRODUCTVARIANTS", t =>
                        {
                            t.HasTrigger("TR_ProductVariants_UpdatedAt");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VariantID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductID")
                        .HasDatabaseName("IX_Reviews_ProductId");

                    b.HasIndex("VariantID");

                    b.HasIndex("OrderID", "ProductID")
                        .IsUnique()
                        .HasDatabaseName("UQ_Order_Product_Review");

                    b.ToTable("REVIEWS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ReviewHelpfulVote", b =>
                {
                    b.Property<int>("VoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoteID"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VoteID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReviewID")
                        .HasDatabaseName("IX_ReviewHelpfulVotes_ReviewId");

                    b.HasIndex("ReviewID", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_ReviewHelpfulVote_Unique");

                    b.ToTable("REVIEWHELPFULVOTES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ReviewImage", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewID")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("ReviewID");

                    b.ToTable("REVIEWIMAGES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ShippingAddress", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressID"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressID");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_DefaultAddress")
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("SHIPPINGADDRESSES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Size", b =>
                {
                    b.Property<int>("SizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SizeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("SizeID");

                    b.ToTable("SIZES");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("SUPPLIERS");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Account", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Customer", "Customer")
                        .WithOne("Account")
                        .HasForeignKey("ClothingStore.Models.Entities.Account", "CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.AccountRole", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Cart", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.CartItem", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Category", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryID");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ChatMessage", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ChatSession", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Account", "Account")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.CouponUsage", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Coupon", "Coupon")
                        .WithMany("CouponUsages")
                        .HasForeignKey("CouponID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.Customer", "Customer")
                        .WithMany("CouponUsages")
                        .HasForeignKey("CustomerId");

                    b.HasOne("ClothingStore.Models.Entities.Order", "Order")
                        .WithMany("CouponUsages")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Customer", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Membership", "Membership")
                        .WithMany("Customers")
                        .HasForeignKey("MembershipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.GoodsIssue", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Order", "Order")
                        .WithMany("GoodsIssues")
                        .HasForeignKey("OrderID");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.GoodsIssueDetail", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.GoodsIssue", "GoodsIssue")
                        .WithMany("GoodsIssueDetails")
                        .HasForeignKey("IssueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.ProductVariant", "ProductVariant")
                        .WithMany("GoodsIssueDetails")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsIssue");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.GoodsReceipt", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Supplier", "Supplier")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.GoodsReceiptDetail", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.GoodsReceipt", "GoodsReceipt")
                        .WithMany("GoodsReceiptDetails")
                        .HasForeignKey("ReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.ProductVariant", "ProductVariant")
                        .WithMany("GoodsReceiptDetails")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Account", "CreatedByAccount")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("ClothingStore.Models.Entities.ProductVariant", "ProductVariant")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAccount");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Order", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Account", "AssignedShipper")
                        .WithMany()
                        .HasForeignKey("AssignedShipperId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClothingStore.Models.Entities.Cart", "Cart")
                        .WithOne("Order")
                        .HasForeignKey("ClothingStore.Models.Entities.Order", "CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("AssignedShipper");

                    b.Navigation("Cart");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.OrderDetail", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.ProductVariant", "ProductVariant")
                        .WithMany("OrderDetails")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Account", "ChangedByAccount")
                        .WithMany("OrderStatusChanges")
                        .HasForeignKey("ChangedBy");

                    b.HasOne("ClothingStore.Models.Entities.Order", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByAccount");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Order", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Product", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.DiscountProgram", "DiscountProgram")
                        .WithMany("Products")
                        .HasForeignKey("ProgramID");

                    b.Navigation("Category");

                    b.Navigation("DiscountProgram");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ProductImage", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.ProductVariant", "ProductVariant")
                        .WithMany("ProductImages")
                        .HasForeignKey("VariantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ProductRelationship", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Product", "LinkedProduct")
                        .WithMany("RelatedByProducts")
                        .HasForeignKey("LinkedProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.Product", "Product")
                        .WithMany("RelatedProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ProductVariant", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Color", "Color")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.Size", "Size")
                        .WithMany("ProductVariants")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Review", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("VariantID");

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ReviewHelpfulVote", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Customer", "Customer")
                        .WithMany("ReviewHelpfulVotes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClothingStore.Models.Entities.Review", "Review")
                        .WithMany("ReviewHelpfulVotes")
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ReviewImage", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Review", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ShippingAddress", b =>
                {
                    b.HasOne("ClothingStore.Models.Entities.Customer", "Customer")
                        .WithMany("ShippingAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Account", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("ChatSessions");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("OrderStatusChanges");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Color", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Coupon", b =>
                {
                    b.Navigation("CouponUsages");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Customer", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Carts");

                    b.Navigation("CouponUsages");

                    b.Navigation("Orders");

                    b.Navigation("ReviewHelpfulVotes");

                    b.Navigation("Reviews");

                    b.Navigation("ShippingAddresses");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.DiscountProgram", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.GoodsIssue", b =>
                {
                    b.Navigation("GoodsIssueDetails");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.GoodsReceipt", b =>
                {
                    b.Navigation("GoodsReceiptDetails");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Membership", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Order", b =>
                {
                    b.Navigation("CouponUsages");

                    b.Navigation("GoodsIssues");

                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");

                    b.Navigation("StatusHistory");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Product", b =>
                {
                    b.Navigation("ProductVariants");

                    b.Navigation("RelatedByProducts");

                    b.Navigation("RelatedProducts");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("GoodsIssueDetails");

                    b.Navigation("GoodsReceiptDetails");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Review", b =>
                {
                    b.Navigation("ReviewHelpfulVotes");

                    b.Navigation("ReviewImages");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Size", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ClothingStore.Models.Entities.Supplier", b =>
                {
                    b.Navigation("GoodsReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
