SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
USE [WEB_CUAHANGQUANAO]
GO

IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID(N'[dbo].[PRODUCTS]') AND name = 'IsBestSeller'
)
BEGIN
    ALTER TABLE [dbo].[PRODUCTS] ADD [IsBestSeller] BIT NOT NULL DEFAULT 0;
END
GO
